language: java

addons:
  apt:
    packages:
      - oracle-java9-installer

jdk:
  - oraclejdk9

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - psql -f $TRAVIS_BUILD_DIR/server/core/src/main/resources/create_schema.sql -U postgres

script:
  - mvn clean test
