language: java

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

script:
  - mvn install -Dskip.unit.tests=true -Dmaven.javadoc.skip=true
  - mvn clean test coveralls:report -P coverage
