language: java

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

services:
  - postgresql

addons:
  postgresql: "9.5"

before_script:
  - psql -f /home/travis/build/blynkkk/blynk-server/core/src/main/resources/create_schema.sql -U postgres

script:
  - mvn clean test
